# Utiliser la dernière image Ubuntu
FROM ubuntu:latest

# Mettre à jour les paquets et upgrader le système
RUN apt-get update && apt-get upgrade -y

# Commande à exécuter au lancement du container
CMD echo "Hello, World!"
